---
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: Function
metadata:
  name: dev-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-east-2
spec:
  name: dev-lambda
  packageType: Image
  code:
    imageURI: 423623836298.dkr.ecr.us-east-2.amazonaws.com/dev/lambda:63d8fb58
  role: arn:aws:iam::423623836298:role/dev-lambda-execution-role
  description: function created by ACK lambda-controller
  timeout: 30
  memorySize: 256
  environment:
    variables:
      S3_BUCKET_NAME: dev-app-output-files-423623836298
      DYNAMODB_TABLE_NAME: dev-pdf-files-per-user-descriptors
