---
# Source: demoapp/charts/lambda/templates/lambda-event-source-mapping.yaml
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: EventSourceMapping
metadata:
  name: dev-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-east-2
spec:
  functionName: dev-lambda
  eventSourceARN: arn:aws:sqs:us-east-2:423623836298:dev-conversion-to-pdf--20250403171511947700000003.fifo
  batchSize: 10
